// Topic clusters — cada pilar agrupa clusters temáticos
// Pilar = página sede | Cluster = subtema | Posts = contenido de cada cluster

export const PILLARS = [
  {
    id: 'diagnostico-empresarial',
    name: 'Diagnóstico',
    slug: 'diagnostico-empresarial',
    description: 'Radiografía de tu negocio. Detecta fugas y oportunidades antes de tomar decisiones.',
    clusters: ['analisis-financiero', 'kpis', 'punto-muerto', 'rentabilidad-real'],
  },
  {
    id: 'precios-y-margenes',
    name: 'Precios',
    slug: 'precios-y-margenes',
    description: 'Cómo poner precio, defender el margen y dejar de malvender tu trabajo.',
    clusters: ['calculo-precios', 'margen-bruto', 'margen-contribucion', 'psicologia-precios'],
  },
  {
    id: 'productos-servicios',
    name: 'Producto/Servicio',
    slug: 'productos-servicios',
    description: 'Lo que vendes importa. Cómo diseñar y diferenciar tu oferta para que no te comparen por precio.',
    clusters: ['diseno-oferta', 'diferenciacion', 'packaging-servicio', 'propuesta-valor'],
  },
  {
    id: 'ventas',
    name: 'Ventas',
    slug: 'ventas',
    description: 'Vender más a los clientes que ya tienes y atraer los que necesitas. Sin descuentos, sin suerte.',
    clusters: ['ticket-medio', 'conversion', 'fidelizacion', 'upselling'],
  },
  {
    id: 'procesos',
    name: 'Procesos',
    slug: 'procesos',
    description: 'Operaciones y sistemas para que tu negocio funcione sin depender de ti.',
    clusters: ['automatizacion', 'estandarizacion', 'productividad', 'control-operaciones'],
  },
  {
    id: 'personas',
    name: 'Personas',
    slug: 'personas',
    description: 'Tu equipo puede multiplicar o destruir tu rentabilidad. Gestión de personas y empleados.',
    clusters: ['contratacion', 'productividad-equipo', 'motivacion', 'despido-rotacion'],
  },
  {
    id: 'marketing-rentable',
    name: 'Publicidad/Marketing',
    slug: 'marketing-rentable',
    description: 'Marketing que genera retorno, no solo visibilidad. Para negocios físicos y locales.',
    clusters: ['roi-marketing', 'captacion-clientes', 'fidelizacion-marketing', 'marketing-local'],
  },
  {
    id: 'emprendimiento',
    name: 'Emprendimiento',
    slug: 'emprendimiento',
    description: 'Montar un negocio rentable desde el principio. Sin errores caros, sin perder el tiempo.',
    clusters: ['validacion', 'modelo-negocio', 'primeros-pasos', 'errores-comunes'],
  },
  {
    id: 'mentalidad',
    name: 'Mentalidad',
    slug: 'mentalidad',
    description: 'La cabeza del empresario es el primer negocio que hay que rentabilizar.',
    clusters: ['mentalidad-empresarial', 'toma-decisiones', 'resiliencia', 'gestion-estres'],
  },
  {
    id: 'liderazgo',
    name: 'Liderazgo',
    slug: 'liderazgo',
    description: 'Dirigir con claridad. Tomar decisiones, gestionar el equipo y crecer sin perder el norte.',
    clusters: ['vision-estrategica', 'comunicacion-equipo', 'delegacion', 'cultura-empresa'],
  },
  {
    id: 'dinero-personal-empresario',
    name: 'Dinero Personal',
    slug: 'dinero-personal-empresario',
    description: 'El negocio debe trabajar para ti. Sueldo, fiscalidad y finanzas personales del dueño.',
    clusters: ['sueldo-empresario', 'finanzas-personales', 'separar-cuentas', 'riqueza'],
  },
]

// Sectores — para la sección especial /sectores
export const SECTORES = [
  { id: 'hosteleria', name: 'Hostelería', slug: 'hosteleria', description: 'Bares, restaurantes y cafeterías.' },
  { id: 'retail', name: 'Comercio / Retail', slug: 'retail', description: 'Tiendas físicas y comercio local.' },
  { id: 'servicios', name: 'Negocios de Servicios', slug: 'servicios', description: 'Autónomos y empresas de servicios.' },
  { id: 'taller', name: 'Talleres y Artesanía', slug: 'taller', description: 'Talleres mecánicos, artesanos y oficios.' },
  { id: 'salud-bienestar', name: 'Salud y Bienestar', slug: 'salud-bienestar', description: 'Clínicas, centros de estética, gimnasios.' },
  { id: 'inmobiliario', name: 'Inmobiliario', slug: 'inmobiliario', description: 'Agencias y negocios del sector inmobiliario.' },
  { id: 'peluqueria', name: 'Peluquería y Estética', slug: 'peluqueria', description: 'Peluquerías, barberías y centros de belleza.' },
  { id: 'formacion', name: 'Academias y Formación', slug: 'formacion', description: 'Academias, autoescuelas y centros de formación.' },
  { id: 'limpieza', name: 'Limpieza y Mantenimiento', slug: 'limpieza', description: 'Empresas de limpieza, reformas y mantenimiento.' },
  { id: 'alimentacion', name: 'Alimentación', slug: 'alimentacion', description: 'Supermercados, fruterías, carnicerías y alimentación.' },
  { id: 'transporte', name: 'Transporte y Logística', slug: 'transporte', description: 'Transporte de mercancías, mensajería y logística.' },
  { id: 'ocio', name: 'Ocio y Entretenimiento', slug: 'ocio', description: 'Centros de ocio, escape rooms, centros deportivos.' },
]

export const CLUSTER_LABELS: Record<string, string> = {
  'analisis-financiero': 'Análisis financiero',
  'kpis': 'KPIs empresariales',
  'punto-muerto': 'Punto de equilibrio',
  'rentabilidad-real': 'Rentabilidad real',
  'calculo-precios': 'Cálculo de precios',
  'margen-bruto': 'Margen bruto',
  'margen-contribucion': 'Margen de contribución',
  'psicologia-precios': 'Psicología de precios',
  'diseno-oferta': 'Diseño de oferta',
  'diferenciacion': 'Diferenciación',
  'packaging-servicio': 'Packaging del servicio',
  'propuesta-valor': 'Propuesta de valor',
  'ticket-medio': 'Ticket medio',
  'conversion': 'Conversión',
  'fidelizacion': 'Fidelización',
  'upselling': 'Upselling y cross-selling',
  'automatizacion': 'Automatización',
  'estandarizacion': 'Estandarización',
  'productividad': 'Productividad',
  'control-operaciones': 'Control de operaciones',
  'contratacion': 'Contratación',
  'productividad-equipo': 'Productividad del equipo',
  'motivacion': 'Motivación',
  'despido-rotacion': 'Despido y rotación',
  'roi-marketing': 'ROI del marketing',
  'captacion-clientes': 'Captación de clientes',
  'fidelizacion-marketing': 'Fidelización',
  'marketing-local': 'Marketing local',
  'validacion': 'Validación de negocio',
  'modelo-negocio': 'Modelo de negocio',
  'primeros-pasos': 'Primeros pasos',
  'errores-comunes': 'Errores comunes',
  'mentalidad-empresarial': 'Mentalidad empresarial',
  'toma-decisiones': 'Toma de decisiones',
  'resiliencia': 'Resiliencia empresarial',
  'gestion-estres': 'Gestión del estrés',
  'vision-estrategica': 'Visión estratégica',
  'comunicacion-equipo': 'Comunicación con el equipo',
  'delegacion': 'Delegación',
  'cultura-empresa': 'Cultura de empresa',
  'sueldo-empresario': 'Sueldo del empresario',
  'finanzas-personales': 'Finanzas personales',
  'separar-cuentas': 'Separar cuentas',
  'riqueza': 'Construcción de riqueza',
}
